from .core import MMH3Media
from .resource_ref import MMH3ResourceRef
from .h3_contract import H3_LATENT_CONTRACT_VERSION, build_h3_latent_contract, h3_latent_contract_from_resource, stale_h3_geometry_contract, validate_h3_continuation_compatibility, validate_h3_geometry_state, validate_h3_latent_contract, validate_h3_refine_compatibility
from .resource_model import CORE_RESOURCE_KINDS, CORE_RESOURCE_ROLES, make_resource_descriptor, normalize_tags, validate_resource_descriptor
from .representations import PACKET_TARGET, REPRESENTATION_KINDS, MAX_REPRESENTATION_BYTES, make_representation_record, representation_is_fresh
from .archive import load_archive, save_archive, get_resource_payload
from .resolution import ResolvedMMH3Inputs, ResolvedReferenceSet, resolve_packet, resolve_reference_set
from .reference_management import ReferenceConfigurationResult, configure_reference
from .reference_cost import ReferenceCostReport, estimate_reference_cost
from .reference_cache import ReferenceCacheLookup, ReferenceCacheSpec, build_reference_cache_spec, compare_reference_cache_latents, lookup_reference_cache
from .preflight import PREFLIGHT_OPERATIONS, PreflightDiagnostic, PreflightReport, preflight_packet
from .generation_contract import H3_CONTINUATION_FAMILIES, GenerationModelContract, infer_h3_model_family, resolve_h3_continuation_family, validate_generation_model_family
from .continuation import H3ContinuationPlan, H3ContinuationResult, build_h3_continuation_handover, build_h3_target_from_prefix, exact_h3_av_handover_boundaries
from .decoded_continuation import DecodedContinuationPlan, DecodedContinuationResult, PreparedDecodedPrefix, encode_decoded_prefix, prepare_decoded_prefix
from .chain import ChainCommitResult, ChainValidation, RerollSourceValidation, commit_chain_segment, start_chain, validate_chain, validate_reroll_source
from .stitch import DecodedSegment, StitchCompatibility, StitchPlan, StitchResult, inspect_stitch_packet, inspect_stitch_packets, materialize_decoded_segment, pcm_boundary, stitch_decoded_segments
from .latent_stitch import H3LatentStitchCompatibility, H3LatentStitchPlan, H3LatentStitchResult, inspect_h3_latent_stitch_packets, stitch_h3_continuation_latents
from .streaming_stitch import StreamingSegment, StreamingStitchResult, StreamingStitchedVideo, build_streaming_stitch, iter_stitched_rgb_frames, materialize_streaming_segment
from .lora_reapply import LoRAReapplyDiagnostic, LoRAReapplyExpansion, LoRAReapplyPlan, build_high_sigma_lora_plan, build_lora_reapply_expansion
from .latent_upscale import UPSCALE_GEOMETRY_MODES, LatentStitchUpscaleTarget, LatentUpscalePlan, LatentUpscaleProcessReport, LatentUpscaleRefineSampling, PreparedLatentUpscale, build_latent_stitch_upscale_target, build_latent_upscale_process_report, build_latent_upscale_refine_sampling, build_latent_upscale_refine_target, plan_latent_upscale_geometry, prepare_decoded_packet_latent_upscale, prepare_packet_latent_upscale
from .spatial_tiles import TILE_BLEND_MODES, TILE_CONTEXT_SOURCES, TILE_MASK_RESIZE_MODES, TILE_OVERLAP_MODES, TILE_TRAVERSALS, SpatialTile, SpatialTilePlan, SpatialTileRunResult, TileRect, plan_spatial_tiles, prepare_spatial_region_mask, run_masked_spatial_video_tiles, run_spatial_video_tiles, validate_masked_spatial_tile_run_report, validate_spatial_tile_plan_report, validate_spatial_tile_run_report
from .h3_tile_refine import NATIVE_H3_TILE_CONTRACT, NativeH3TileRefineResult, run_native_h3_tile_refine, validate_native_h3_tile_refine_report
from .tile_backend import TILE_BACKEND_OVERLAP_MODES, TileBackendFinalizeResult, finalize_external_tile_latents, finalize_external_tile_video, tile_backend_fingerprint_from_preflight, validate_external_tile_finalize_report
from .control_contract import H3_CONTROL_ALGORITHMS, H3_CONTROL_ALGORITHM_CONTEXTS, H3_CONTROL_AUTO_PREFERENCES, H3_CONTROL_CONTEXT_ALGORITHMS, H3_CONTROLNET_ALGORITHMS, H3_CONTROL_KINDS, H3_CONTROL_KIND_OPTIONS, H3_CONTROL_RESOURCE_ROLES, H3_CONTROL_TEMPORAL_POLICIES, ControlAlgorithmResolution, ControlDiagnostic, ControlPreprocessor, ControlProviderProvenance, H3ControlConfiguration, build_control_configuration, control_configuration_from_dict, get_control_configuration, resolve_control_algorithm, set_control_configuration
from .control_preflight import CONTROLNET_LOADER_NODE_ID, H3_CONTROL_APPLY_NODE_ID, H3ControlCapabilityReport, RuntimeNodeContract, parse_controlnet_loader_contract, parse_h3_control_apply_contract, preflight_h3_control
from .control_provider import (
    H3ControlApplyPlan,
    H3ControlExpansion,
    H3ControlProviderAdapter,
    MaterializedControlVideo,
    align_control_timeline,
    bind_control_capability,
    build_control_apply_plan,
    build_control_pass_through_info,
    build_h3_control_expansion,
    control_provider_for_algorithm,
    materialize_control_video,
    normalize_control_apply_process_info,
    prepare_control_inputs,
    validate_masked_edit_inputs,
)
from .control_tiles import (
    H3_CONTROL_TILE_CONTRACT,
    H3TileControlInputs,
    apply_control_to_conditioning,
    build_tiled_control_process_info,
    clone_guider_with_conditioning,
    crop_control_inputs_for_tile,
)
from .sampling_presets import (
    CUSTOM_PROFILE,
    PROFILE_PRESETS,
    SAMPLING_PRESET_CONTRACT,
    SAMPLING_PROFILES,
    STANDARD_PROFILE,
    TURBO_4_PROFILE,
    TURBO_8_PROFILE,
    TURBO_RECIPES,
    SamplingPreset,
    build_sampling_preset,
)
from .model_optimizations import (
    ATTENTION_MODES,
    FP16_ACCUMULATION_MODES,
    MODEL_OPTIMIZATION_CONTRACT,
    ModelOptimizationExpansion,
    ModelOptimizationPlan,
    build_model_optimization_expansion,
    build_model_optimization_plan,
)
from .generation_settings import GenerationSettings, adapt_h3_canvas, build_generation_settings
from .automation import ChunkExecutionSelection, ChunkPlan, VIDEO_SUFFIXES, append_h3_audio_interactive_try, finalize_h3_audio_interactive_plan, plan_batch_inputs, plan_h3_audio_interactive_sequence, plan_h3_audio_timeline_chunks, plan_long_video_chunks, resolve_chunk_execution
from .automation_batch_stitch import BATCH_STITCH_CONTRACT, BatchStitchPreparation, inspect_batch_stitch_plan, prepare_batch_stitch
from .raw_video_import import ConformSettings, RawImportResult, RawVideoProbe, import_raw_video, normalize_batch_plan, probe_raw_video
from .automation_adapters import AudioTimelineChunkExpansion, VideoChunkExpansion, build_audio_timeline_chunk_expansion, build_video_chunk_expansion, trim_audio_samples, trim_audio_samples_padded
from .automation_estimate import PREQUEUE_ESTIMATE_CONTRACT, build_prequeue_estimate, prequeue_summary
from .automation_assembly import ChunkAssemblyResult, assemble_chunk_packets, load_immutable_lipsync_audio
from .automation_upscale import build_long_video_upscale_settings, validate_upscale_chunk_artifact
from .automation_lipsync import (
    PROOF_CONTRACT as LIPSYNC_PROOF_CONTRACT,
    SETTINGS_CONTRACT as LIPSYNC_SETTINGS_CONTRACT,
    build_h3_audio_sync_chunk_proof,
    build_long_video_audio_sync_settings,
    extend_long_video_audio_sync_settings,
    update_audio_delivery_policy,
    validate_lipsync_chunk_proof,
)
from .automation_execution import EXECUTION_CONTRACT, JOB_STATES, accept_execution_candidate, acquire_next_execution_job, append_interactive_audio_try, build_chunk_assembly_map, commit_execution_artifact, commit_execution_candidate, create_execution_ledger, deterministic_artifact_prefix, finalize_interactive_audio_sequence, load_execution_ledger, save_execution_ledger, set_execution_audio_delivery_policy, select_resume_jobs, transition_execution_job

__all__ = [
    "MMH3Media",
    "MMH3ResourceRef",
    "H3_LATENT_CONTRACT_VERSION",
    "build_h3_latent_contract",
    "h3_latent_contract_from_resource",
    "stale_h3_geometry_contract",
    "validate_h3_continuation_compatibility",
    "validate_h3_geometry_state",
    "validate_h3_latent_contract",
    "validate_h3_refine_compatibility",
    "CORE_RESOURCE_KINDS",
    "CORE_RESOURCE_ROLES",
    "make_resource_descriptor",
    "normalize_tags",
    "validate_resource_descriptor",
    "PACKET_TARGET",
    "REPRESENTATION_KINDS",
    "MAX_REPRESENTATION_BYTES",
    "make_representation_record",
    "representation_is_fresh",
    "H3_CONTROL_ALGORITHMS",
    "H3_CONTROL_ALGORITHM_CONTEXTS",
    "H3_CONTROL_AUTO_PREFERENCES",
    "H3_CONTROL_CONTEXT_ALGORITHMS",
    "H3_CONTROLNET_ALGORITHMS",
    "H3_CONTROL_KINDS",
    "H3_CONTROL_KIND_OPTIONS",
    "H3_CONTROL_RESOURCE_ROLES",
    "H3_CONTROL_TEMPORAL_POLICIES",
    "CONTROLNET_LOADER_NODE_ID",
    "H3_CONTROL_APPLY_NODE_ID",
    "ControlDiagnostic",
    "ControlAlgorithmResolution",
    "ControlPreprocessor",
    "ControlProviderProvenance",
    "H3ControlConfiguration",
    "H3ControlCapabilityReport",
    "RuntimeNodeContract",
    "H3ControlApplyPlan",
    "H3ControlExpansion",
    "H3ControlProviderAdapter",
    "MaterializedControlVideo",
    "H3TileControlInputs",
    "H3_CONTROL_TILE_CONTRACT",
    "GenerationModelContract",
    "H3_CONTINUATION_FAMILIES",
    "H3ContinuationPlan",
    "H3ContinuationResult",
    "DecodedContinuationPlan",
    "DecodedContinuationResult",
    "PreparedDecodedPrefix",
    "ChainCommitResult",
    "ChainValidation",
    "RerollSourceValidation",
    "DecodedSegment",
    "StitchCompatibility",
    "StitchPlan",
    "StitchResult",
    "H3LatentStitchCompatibility",
    "H3LatentStitchPlan",
    "H3LatentStitchResult",
    "StreamingSegment",
    "StreamingStitchResult",
    "StreamingStitchedVideo",
    "LoRAReapplyDiagnostic",
    "LoRAReapplyExpansion",
    "LoRAReapplyPlan",
    "LatentStitchUpscaleTarget",
    "LatentUpscalePlan",
    "LatentUpscaleProcessReport",
    "LatentUpscaleRefineSampling",
    "PreparedLatentUpscale",
    "UPSCALE_GEOMETRY_MODES",
    "TILE_BLEND_MODES",
    "TILE_CONTEXT_SOURCES",
    "TILE_MASK_RESIZE_MODES",
    "TILE_OVERLAP_MODES",
    "TILE_TRAVERSALS",
    "TILE_BACKEND_OVERLAP_MODES",
    "TileRect",
    "SpatialTile",
    "SpatialTilePlan",
    "SpatialTileRunResult",
    "TileBackendFinalizeResult",
    "NativeH3TileRefineResult",
    "NATIVE_H3_TILE_CONTRACT",
    "ReferenceConfigurationResult",
    "ReferenceCostReport",
    "ReferenceCacheLookup",
    "ReferenceCacheSpec",
    "PREFLIGHT_OPERATIONS",
    "PreflightDiagnostic",
    "PreflightReport",
    "ResolvedMMH3Inputs",
    "ResolvedReferenceSet",
    "configure_reference",
    "build_reference_cache_spec",
    "build_h3_continuation_handover",
    "build_h3_target_from_prefix",
    "build_streaming_stitch",
    "build_high_sigma_lora_plan",
    "build_lora_reapply_expansion",
    "plan_latent_upscale_geometry",
    "plan_spatial_tiles",
    "prepare_spatial_region_mask",
    "run_masked_spatial_video_tiles",
    "validate_masked_spatial_tile_run_report",
    "run_spatial_video_tiles",
    "run_native_h3_tile_refine",
    "validate_native_h3_tile_refine_report",
    "finalize_external_tile_video",
    "finalize_external_tile_latents",
    "tile_backend_fingerprint_from_preflight",
    "validate_external_tile_finalize_report",
    "validate_spatial_tile_plan_report",
    "validate_spatial_tile_run_report",
    "prepare_packet_latent_upscale",
    "prepare_decoded_packet_latent_upscale",
    "build_latent_stitch_upscale_target",
    "build_latent_upscale_process_report",
    "build_latent_upscale_refine_sampling",
    "build_latent_upscale_refine_target",
    "encode_decoded_prefix",
    "commit_chain_segment",
    "compare_reference_cache_latents",
    "estimate_reference_cost",
    "exact_h3_av_handover_boundaries",
    "lookup_reference_cache",
    "inspect_stitch_packets",
    "inspect_h3_latent_stitch_packets",
    "stitch_h3_continuation_latents",
    "inspect_stitch_packet",
    "materialize_decoded_segment",
    "materialize_streaming_segment",
    "pcm_boundary",
    "infer_h3_model_family",
    "resolve_h3_continuation_family",
    "preflight_packet",
    "prepare_decoded_prefix",
    "get_resource_payload",
    "load_archive",
    "resolve_packet",
    "resolve_reference_set",
    "save_archive",
    "start_chain",
    "stitch_decoded_segments",
    "iter_stitched_rgb_frames",
    "validate_chain",
    "validate_reroll_source",
    "validate_generation_model_family",
    "build_control_configuration",
    "control_configuration_from_dict",
    "get_control_configuration",
    "set_control_configuration",
    "resolve_control_algorithm",
    "parse_controlnet_loader_contract",
    "parse_h3_control_apply_contract",
    "preflight_h3_control",
    "align_control_timeline",
    "bind_control_capability",
    "build_control_apply_plan",
    "build_control_pass_through_info",
    "build_h3_control_expansion",
    "control_provider_for_algorithm",
    "prepare_control_inputs",
    "normalize_control_apply_process_info",
    "materialize_control_video",
    "validate_masked_edit_inputs",
    "crop_control_inputs_for_tile",
    "apply_control_to_conditioning",
    "clone_guider_with_conditioning",
    "build_tiled_control_process_info",
    "ATTENTION_MODES",
    "CUSTOM_PROFILE",
    "FP16_ACCUMULATION_MODES",
    "MODEL_OPTIMIZATION_CONTRACT",
    "PROFILE_PRESETS",
    "SAMPLING_PRESET_CONTRACT",
    "SAMPLING_PROFILES",
    "STANDARD_PROFILE",
    "TURBO_4_PROFILE",
    "TURBO_8_PROFILE",
    "TURBO_RECIPES",
    "ModelOptimizationExpansion",
    "ModelOptimizationPlan",
    "SamplingPreset",
    "build_model_optimization_expansion",
    "build_model_optimization_plan",
    "build_sampling_preset",
    "GenerationSettings",
    "adapt_h3_canvas",
    "build_generation_settings",
    "ChunkPlan",
    "ChunkExecutionSelection",
    "AudioTimelineChunkExpansion",
    "VideoChunkExpansion",
    "ChunkAssemblyResult",
    "VIDEO_SUFFIXES",
    "RawVideoProbe",
    "ConformSettings",
    "RawImportResult",
    "probe_raw_video",
    "import_raw_video",
    "normalize_batch_plan",
    "BATCH_STITCH_CONTRACT",
    "BatchStitchPreparation",
    "prepare_batch_stitch",
    "plan_batch_inputs",
    "plan_h3_audio_timeline_chunks",
    "plan_h3_audio_interactive_sequence",
    "append_h3_audio_interactive_try",
    "finalize_h3_audio_interactive_plan",
    "plan_long_video_chunks",
    "PREQUEUE_ESTIMATE_CONTRACT",
    "build_prequeue_estimate",
    "prequeue_summary",
    "inspect_batch_stitch_plan",
    "resolve_chunk_execution",
    "build_audio_timeline_chunk_expansion",
    "build_video_chunk_expansion",
    "trim_audio_samples",
    "trim_audio_samples_padded",
    "assemble_chunk_packets",
    "load_immutable_lipsync_audio",
    "build_long_video_upscale_settings",
    "validate_upscale_chunk_artifact",
    "LIPSYNC_PROOF_CONTRACT",
    "LIPSYNC_SETTINGS_CONTRACT",
    "validate_lipsync_chunk_proof",
    "extend_long_video_audio_sync_settings",
    "update_audio_delivery_policy",
    "EXECUTION_CONTRACT",
    "JOB_STATES",
    "build_chunk_assembly_map",
    "acquire_next_execution_job",
    "accept_execution_candidate",
    "append_interactive_audio_try",
    "commit_execution_artifact",
    "commit_execution_candidate",
    "create_execution_ledger",
    "deterministic_artifact_prefix",
    "finalize_interactive_audio_sequence",
    "load_execution_ledger",
    "save_execution_ledger",
    "set_execution_audio_delivery_policy",
    "select_resume_jobs",
    "transition_execution_job",
]
